name: Deploy Node.js Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Docker Image
        run: |
          docker build -t kirankhadka/kiran-node-server:latest .
          docker push kirankhadka/kiran-node-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.27.3.39
          username: ubuntu
          key: ${{ secrets.AWS_PEM_KEY }}
          port: 22
          script: |
            # Remove existing container if it exists
            docker rm -f kiran-node-server || true

            # Pull the latest image
            docker pull kirankhadka/kiran-node-server:latest

            # Run a new container
            docker run -d \
              --name kiran-node-server \
              --restart unless-stopped \
              -p 8000:8000 \
              kirankhadka/kiran-node-server:latest